//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string id { get; set; }
        public string hebrewName { get; set; }
        public string englishName { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public Nullable<int> city_code { get; set; }
        public Nullable<int> bank { get; set; }
        public Nullable<int> bank_branch { get; set; }
        public string account_number { get; set; }
    
        public virtual City City { get; set; }
    }
}
